language: perl
sudo: false

perl:
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"

before_install:
    - cpanm --quiet --notest Dist::Zilla
    - dzil authordeps | cpanm --quiet --notest
install:
    - dzil listdeps | cpanm --quiet --notest
script:
    - dzil test
