language: perl
sudo: false

perl:
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"

before_install:
  - git config --global user.email "dancer-dev@dancer.pm"
  - git config --global user.name "Perl Dancer dev team"
  - cpanm --quiet --notest Dist::Zilla
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init --auto
